// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCesQHT--VbfUq6Ti3pzEyzkaTsvEd5aoM',
    appId: '1:65057465178:web:de041faa8be3be012cc963',
    messagingSenderId: '65057465178',
    projectId: 'm-flow-a2d00',
    authDomain: 'm-flow-a2d00.firebaseapp.com',
    storageBucket: 'm-flow-a2d00.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwyomajVhKKHodRsjC0Vqv9b4EphE1nnI',
    appId: '1:65057465178:ios:6dd4d2d4f2b51d572cc963',
    messagingSenderId: '65057465178',
    projectId: 'm-flow-a2d00',
    storageBucket: 'm-flow-a2d00.appspot.com',
    iosBundleId: 'com.example.mFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCesQHT--VbfUq6Ti3pzEyzkaTsvEd5aoM',
    appId: '1:65057465178:web:eeb922917bee5e072cc963',
    messagingSenderId: '65057465178',
    projectId: 'm-flow-a2d00',
    authDomain: 'm-flow-a2d00.firebaseapp.com',
    storageBucket: 'm-flow-a2d00.appspot.com',
  );

}